# Generated by Django 6.0.3 on 2026-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_lga_remove_student_overall_score_exams_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
