# Generated by Django 6.0.3 on 2026-03-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0004_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('state_official', 'State_Official')], default='Teacher', max_length=20),
        ),
    ]
