# Generated by Django 6.0.3 on 2026-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('state_official', 'State_Official')], default='teacher', max_length=20),
        ),
    ]
