# Generated by Django 6.0.3 on 2026-03-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='subject',
        ),
    ]
