# Generated by Django 6.0.3 on 2026-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0007_remove_exams_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
