# Generated by Django 6.0.3 on 2026-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0008_exams_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_type',
            field=models.CharField(choices=[('waec', 'WAEC'), ('neco', 'NECO')], default='none', max_length=20),
        ),
    ]
