# Generated by Django 6.0.3 on 2026-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0009_exams_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('student', 'subject', 'year')},
        ),
    ]
